MyPaint: Utility.o Main.o Methods.o
	gcc -o cpu Main.o Utility.o Methods.o -lm

Main.o:
	gcc -o Main.o -c MyPaint.c

Methods.o:
	gcc -o Methods.o -c CPU_methods.c
	
Utility.o:
	gcc -o Utility.o -c pgmUtility.c


